# **Python Tutorial**
**Created by Mustafa Germec, PhD**

## **16. Arrays in Python**

* Array is a container which can hold a fix number of items and these items should be of the same type. 
* Most of the data structures make use of arrays to implement their algorithms.
* Lists can be used to form arrays.
* Following are the important terms to understand the concept of Array. 
<ul>
<li><b>Element:</b> Each item stored in an array is called an element.</li>
<li><b>Index:</b> Each location of an element in an array has a numerical index, which is used to identify the element.</li>
</ul>

<img src="https://favtutor.com/resources/images/uploads/mceu_61653743011611745415316.jpg" width ='600' alt='python_arrays' />

* Array index begins with 0.
* Each element in the array can be accessed with its index number.
* The length of the array describes the capacity to store the elements.
* Basic array operations are **Traverse, Insertion, Deletion, Search, and Update.**

### **Creating an array**
You should import the module name **'array'** as follows:
* **import array** or **from array import (*)**.
* **(*)** means that it covers all features of the array.

In [4]:
# Import the module
import array as arr
from array import *

In [5]:
# To access more information regarding array, you can execute the following commands
help(arr)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array
    
    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |  
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |  
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined

### **Type code**
- Arrays represent basic values and behave very much like lists, except the type of objects stored in them is constrained. 
- The type is specified at object creation time by using a type code, which is a single character.
- The following type codes are defined:

<img src='https://www.askpython.com/wp-content/uploads/2019/09/python-array-supported-type-code-1024x624.png' width = '600' alt='type_code'>

In [6]:
special_nums = arr.array('d', [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
for i in special_nums:
    print(i)

0.577
1.618
2.718
3.14
6.0
37.0
1729.0


### **Accessing**

In [7]:
special_nums = arr.array('d', [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
print(f'First element of numbers is {special_nums[0]}, called euler constant.')
print(f'Second element of numbers is {special_nums[1]}, called golden_ratio.')
print(f'Last element of numbers is {special_nums[-1]}, called Ramanujan-Hardy number.')

First element of numbers is 0.577, called euler constant.
Second element of numbers is 1.618, called golden_ratio.
Last element of numbers is 1729.0, called Ramanujan-Hardy number.


### **Changing or Updating**

In [8]:
nums = arr.array('i', [0, 1, 1, 2, 3, 5, 8, 13, 21, 34])

# Changing the first element of the array
nums[0] = 55
print(nums)

# Changing 2nd to 4th elements of the array
nums[1:4] =arr.array('i', [89, 144, 233, 377])
print(nums)

array('i', [55, 1, 1, 2, 3, 5, 8, 13, 21, 34])
array('i', [55, 89, 144, 233, 377, 3, 5, 8, 13, 21, 34])


### **Deleting**

In [9]:
nums = arr.array('i', [0, 1, 1, 2, 3, 5, 8, 13, 21, 34])

# Deleting the first element of the array
del nums[0]
print(nums)

# Deleting the 2nd to 4th elements of the array
del nums[1:4]
print(nums)

array('i', [1, 1, 2, 3, 5, 8, 13, 21, 34])
array('i', [1, 5, 8, 13, 21, 34])


### **Lenght of the array**

In [10]:
special_nums = arr.array('d', [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
print(f'The length of the array is {len(special_nums)}.')

The length of the array is 7.


### **Concatenation**

In [11]:
special_nums = arr.array('d', [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
fibonacci_nums = arr.array('d', [1, 1, 2, 3, 5, 8, 13, 21, 34])
special_fibonacci_nums = arr.array('d')
special_fibonacci_nums = special_nums + fibonacci_nums
print(f'The new array called special_fibonacci_nums is {special_fibonacci_nums}.')

The new array called special_fibonacci_nums is array('d', [0.577, 1.618, 2.718, 3.14, 6.0, 37.0, 1729.0, 1.0, 1.0, 2.0, 3.0, 5.0, 8.0, 13.0, 21.0, 34.0]).


### **Creating ID arrays**

In [12]:
mult = 10
one_array = [1]*mult
print(one_array)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [13]:
mult = 10
nums_array = [i for i in range(mult)]
print(nums_array)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### **Addition with the functions insert() and append()**

In [14]:
# Using the function 'insert()'
fibonacci_nums = arr.array('i', [1, 1, 2, 3, 5, 8, 13, 21, 34])
print('Before any additon into fibonacci numbers')
for i in fibonacci_nums:
    print(i, end = ' ')
print()
print('After an element additon into fibonacci numbers')
added_num = fibonacci_nums[-1] + fibonacci_nums[-2]
fibonacci_nums.insert(9, added_num)
for i in fibonacci_nums:    
    print(i, end = ' ')
print()
print('After an element additon into fibonacci numbers')
added_num = fibonacci_nums[-1] + fibonacci_nums[-2]
fibonacci_nums.insert(10, added_num)
for i in fibonacci_nums:    
    print(i, end = ' ')

Before any additon into fibonacci numbers
1 1 2 3 5 8 13 21 34 
After an element additon into fibonacci numbers
1 1 2 3 5 8 13 21 34 55 
After an element additon into fibonacci numbers
1 1 2 3 5 8 13 21 34 55 89 

In [15]:
# Using the function 'append()'
fibonacci_nums = arr.array('i', [1, 1, 2, 3, 5, 8, 13, 21, 34])
print('Before any additon into fibonacci numbers')
for i in fibonacci_nums:
    print(i, end = ' ')
print()
print('After an element additon into fibonacci numbers')
added_num = fibonacci_nums[-1] + fibonacci_nums[-2]
fibonacci_nums.append(added_num)
for i in fibonacci_nums:    
    print(i, end = ' ')
print()
print('After an element additon into fibonacci numbers')
added_num = fibonacci_nums[-1] + fibonacci_nums[-2]
fibonacci_nums.append(added_num)
for i in fibonacci_nums:    
    print(i, end = ' ')

Before any additon into fibonacci numbers
1 1 2 3 5 8 13 21 34 
After an element additon into fibonacci numbers
1 1 2 3 5 8 13 21 34 55 
After an element additon into fibonacci numbers
1 1 2 3 5 8 13 21 34 55 89 

### **Removing with the function remove() and pop()**

In [16]:
# Using the function 'remove()'
special_nums = arr.array('d', [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
print('Before removing an element from the array')
for i in special_nums:
    print(i, end = ' ')
print()
print('After removing an element from the array')
special_nums.remove(0.577)
for i in special_nums:
    print(i, end=' ')
print()
print('After removing one more element from the array')
special_nums.remove(special_nums[0])      # We can make this using indexing
for i in special_nums:
    print(i, end=' ')

Before removing an element from the array
0.577 1.618 2.718 3.14 6.0 37.0 1729.0 
After removing an element from the array
1.618 2.718 3.14 6.0 37.0 1729.0 
After removing one more element from the array
2.718 3.14 6.0 37.0 1729.0 

In [17]:
# Using the function 'pop()'
# The function pop() removes the last element from the array
special_nums = arr.array('d', [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
print('Before removing an element from the array')
for i in special_nums:
    print(i, end = ' ')
print()
print('After removing last element from the array')
special_nums.pop()
for i in special_nums:
    print(i, end=' ')
print()
print('After removing one more last element from the array')
special_nums.pop()
for i in special_nums:
    print(i, end=' ')
print()
print('After removing one more element using index from the array')
special_nums.pop(3)         # It deleted the pi number
for i in special_nums:
    print(i, end=' ')
print()

Before removing an element from the array
0.577 1.618 2.718 3.14 6.0 37.0 1729.0 
After removing last element from the array
0.577 1.618 2.718 3.14 6.0 37.0 
After removing one more last element from the array
0.577 1.618 2.718 3.14 6.0 
After removing one more element using index from the array
0.577 1.618 2.718 6.0 


### **Slicing**

In [18]:
special_nums = arr.array('d', [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
sliced_special_nums = special_nums[1:5]     # It returns between index 1 and index 4, not index 5. 
print(sliced_special_nums)
# or using for loop
for i in sliced_special_nums:
    print(i, end = " ")

array('d', [1.618, 2.718, 3.14, 6.0])
1.618 2.718 3.14 6.0 

In [19]:
special_nums = arr.array('d', [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
sliced_special_nums = special_nums[3:]          # It returns index 3 and later. 
print(sliced_special_nums)

array('d', [3.14, 6.0, 37.0, 1729.0])


In [20]:
special_nums = arr.array('d', [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
sliced_special_nums = special_nums[:3]          # It returns until index 2, not index 3. 
print(sliced_special_nums)

array('d', [0.577, 1.618, 2.718])


In [21]:
special_nums = arr.array('d', [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
sliced_special_nums = special_nums[:]       # It returns all elements in the array
print(sliced_special_nums)

array('d', [0.577, 1.618, 2.718, 3.14, 6.0, 37.0, 1729.0])


In [22]:
special_nums = arr.array('d', [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
sliced_special_nums = special_nums[::-1]        # It reverses the array. 
print(sliced_special_nums)

array('d', [1729.0, 37.0, 6.0, 3.14, 2.718, 1.618, 0.577])


### **Searching**

In [23]:
# To make a search in an array, use the function index()
special_nums = arr.array('d', [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
searched_item = special_nums.index(2.718)
print(f'The searched item euler number 2.718 is present at index {searched_item}.')
# printing with format
print('The searched item euler number {} is present at index {}.'.format(2.718, searched_item))

The searched item euler number 2.718 is present at index 2.
The searched item euler number 2.718 is present at index 2.


### **Copying**

#### Copying using assignment
This process gives the same ID number.

In [24]:
special_nums = arr.array('d', [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
copied_special_nums = special_nums
print(special_nums, 'with the ID number', id(special_nums))
print(copied_special_nums, 'with the ID number', id(copied_special_nums))

# Using for loop
for i in special_nums:
    print(i, end= ' ')
print()
print(f'The ID number of the array special_nums is {id(special_nums)}.')
for i in copied_special_nums:
    print(i, end= ' ')
print()
print(f'The ID number of the array copied_special_nums is {id(copied_special_nums)}.')

array('d', [0.577, 1.618, 2.718, 3.14, 6.0, 37.0, 1729.0]) with the ID number 2668250199472
array('d', [0.577, 1.618, 2.718, 3.14, 6.0, 37.0, 1729.0]) with the ID number 2668250199472
0.577 1.618 2.718 3.14 6.0 37.0 1729.0 
The ID number of the array special_nums is 2668250199472.
0.577 1.618 2.718 3.14 6.0 37.0 1729.0 
The ID number of the array copied_special_nums is 2668250199472.


#### Copying using view()
This process gives the different ID number.

In [25]:
# import numpy library
import numpy as np

# Copying the array
special_nums = np.array( [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
copied_special_nums = special_nums.view()
print(special_nums, 'with the ID number', id(special_nums))
print(copied_special_nums, 'with the ID number', id(copied_special_nums))

#Using for loop
for i in special_nums:
    print(i, end = ' ')
print()
for i in copied_special_nums:
    print(i, end = ' ')


[5.770e-01 1.618e+00 2.718e+00 3.140e+00 6.000e+00 3.700e+01 1.729e+03] with the ID number 2668248532144
[5.770e-01 1.618e+00 2.718e+00 3.140e+00 6.000e+00 3.700e+01 1.729e+03] with the ID number 2668254732400
0.577 1.618 2.718 3.14 6.0 37.0 1729.0 
0.577 1.618 2.718 3.14 6.0 37.0 1729.0 

#### Copying using copy()
This process gives the different ID number.

In [26]:
# import numpy library
import numpy as np

# Copying the array
special_nums = np.array( [0.577, 1.618, 2.718, 3.14, 6, 37, 1729])
copied_special_nums = special_nums.copy()
print(special_nums, 'with the ID number', id(special_nums))
print(copied_special_nums, 'with the ID number', id(copied_special_nums))

#Using for loop
for i in special_nums:
    print(i, end = ' ')
print()
for i in copied_special_nums:
    print(i, end = ' ')


[5.770e-01 1.618e+00 2.718e+00 3.140e+00 6.000e+00 3.700e+01 1.729e+03] with the ID number 2668254735376
[5.770e-01 1.618e+00 2.718e+00 3.140e+00 6.000e+00 3.700e+01 1.729e+03] with the ID number 2668254736144
0.577 1.618 2.718 3.14 6.0 37.0 1729.0 
0.577 1.618 2.718 3.14 6.0 37.0 1729.0 